# Generated by Django 6.0.4 on 2026-04-24 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteuser',
            name='special_user',
            field=models.CharField(choices=[('user', 'user'), ('admin', 'admin'), ('superadmin', 'superadmin')], default='user', max_length=20),
        ),
    ]
