# Generated by Django 6.0.4 on 2026-04-24 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_api', '0002_alter_siteuser_special_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteuser',
            name='special_user',
        ),
        migrations.AddField(
            model_name='siteuser',
            name='role',
            field=models.CharField(choices=[('CUSTOMER', 'Customer'), ('VENDOR', 'Vendor'), ('ADMIN', 'Admin')], default='CUSTOMER', max_length=10),
        ),
        migrations.AlterField(
            model_name='siteuser',
            name='shipping_address',
            field=models.TextField(blank=True),
        ),
    ]
