# Generated by Django 6.0.4 on 2026-04-24 04:40

import product_api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='photo',
            field=models.ImageField(blank=True, upload_to=product_api.models.upload_loaction),
        ),
    ]
